# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: circuit_breaker.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import http_pb2 as http__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ircuit_breaker.proto\x1a\nhttp.proto\"\x98\x01\n\x15\x43ircuitBreakerRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12!\n\x08\x65xpected\x18\x02 \x03(\x0e\x32\x0f.HTTPStatusCode\x12\x0f\n\x07timeout\x18\x03 \x01(\r\x12\x11\n\tthreshold\x18\x04 \x01(\r\x12\x10\n\x08recovery\x18\x05 \x01(\r\x12\x1a\n\x04http\x18\x06 \x01(\x0b\x32\x0c.HTTPRequest\"v\n\x16\x43ircuitBreakerResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.CircuitBreakerStatus\x12\x0c\n\x04wait\x18\x03 \x01(\r\x12\x1b\n\x04http\x18\x04 \x01(\x0b\x32\r.HTTPResponse*h\n\x14\x43ircuitBreakerStatus\x12\x19\n\x15\x43ircuitBreaker_CLOSED\x10\x00\x12\x1c\n\x18\x43ircuitBreaker_HALF_OPEN\x10\x01\x12\x17\n\x13\x43ircuitBreaker_OPEN\x10\x02\x32I\n\x0e\x43ircuitBreaker\x12\x37\n\x04send\x12\x16.CircuitBreakerRequest\x1a\x17.CircuitBreakerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'circuit_breaker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CIRCUITBREAKERSTATUS']._serialized_start=312
  _globals['_CIRCUITBREAKERSTATUS']._serialized_end=416
  _globals['_CIRCUITBREAKERREQUEST']._serialized_start=38
  _globals['_CIRCUITBREAKERREQUEST']._serialized_end=190
  _globals['_CIRCUITBREAKERRESPONSE']._serialized_start=192
  _globals['_CIRCUITBREAKERRESPONSE']._serialized_end=310
  _globals['_CIRCUITBREAKER']._serialized_start=418
  _globals['_CIRCUITBREAKER']._serialized_end=491
# @@protoc_insertion_point(module_scope)
