#
#  manifest.yaml
#  Progetto di Distributed Systems and Big Data
#  Anno Accademico 2024-25
#  (C) 2024 Luca Montera, Alessio Giordano
#
#  Created by Alessio Giordano on 10/01/25.
#

kind: Namespace
apiVersion: v1
metadata:
    name: why-finance
    labels:
        name: why-finance
---
kind: Service
apiVersion: v1
metadata:
    name: circuit-breaker-redis
    labels:
        app: circuit-breaker-redis
    namespace: why-finance
spec:
    ports:
    - name: redis
      port: 6379
    selector:
        app: circuit-breaker-redis
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: circuit-breaker-redis
    labels:
        app: circuit-breaker-redis
    namespace: why-finance
spec:
    replicas: 1
    selector:
        matchLabels:
            app: circuit-breaker-redis
    template:
        metadata:
            labels:
                app: circuit-breaker-redis
        spec:
            containers:
            - name: circuit-breaker-redis
              image: redis:alpine
              imagePullPolicy: IfNotPresent # Always # Never
              ports:
              - containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
    name: circuit-breaker
    labels:
        app: circuit-breaker
    namespace: why-finance
spec:
    ports:
    - name: grpc
      port: 30112
    selector:
        app: circuit-breaker
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: circuit-breaker
    labels:
        app: circuit-breaker
    namespace: why-finance
spec:
    replicas: 1
    selector:
        matchLabels:
            app: circuit-breaker
    template:
        metadata:
            labels:
                app: circuit-breaker
        spec:
            initContainers:
            - name: circuit-breaker-init
              image: redis:alpine
              command: ['sh', '-c', 'until nc -z circuit-breaker-redis 6379; do echo "Waiting for Redis"; sleep 1; done;']
            containers:
            - name: circuit-breaker
              image: circuit-breaker:latest
              imagePullPolicy: IfNotPresent # Always # Never
              ports:
              - containerPort: 30112
              env:
              - name: REDIS_PORT
                valueFrom:
                    configMapKeyRef:
                        name: why-finance-env
                        key: REDIS_PORT
              - name: CIRCUIT_BREAKER_PORT
                valueFrom:
                    configMapKeyRef:
                        name: why-finance-env
                        key: CIRCUIT_BREAKER_PORT