#
#  manifest.yaml
#  Progetto di Distributed Systems and Big Data
#  Anno Accademico 2024-25
#  (C) 2024 Luca Montera, Alessio Giordano
#
#  Created by Alessio Giordano on 10/01/25.
#

kind: Namespace
apiVersion: v1
metadata:
    name: why-finance
    labels:
        name: why-finance
---
kind: Service
apiVersion: v1
metadata:
    name: broker
    labels:
        app: broker
    namespace: why-finance
spec:
    ports:
    - name: plaintext
      port: 9092
    - name: controller
      port: 9093
    selector:
        app: broker
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: broker
    labels:
        app: broker
    namespace: why-finance
spec:
    replicas: 1
    selector:
        matchLabels:
            app: broker
    template:
        metadata:
            labels:
                app: broker
        spec:
            containers:
            - name: broker
              image: apache/kafka:3.7.2
              imagePullPolicy: IfNotPresent # Always # Never
              ports:
              - containerPort: 9092
              - containerPort: 9093
              env:
              - name: KAFKA_NODE_ID
                value: "1"
              - name: KAFKA_PROCESS_ROLES
                value: "broker,controller"
              - name: KAFKA_LISTENERS
                value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
              - name: KAFKA_ADVERTISED_LISTENERS
                value: "PLAINTEXT://broker:9092"
              - name: KAFKA_CONTROLLER_LISTENER_NAMES
                value: "CONTROLLER"
              - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
              - name: KAFKA_CONTROLLER_QUORUM_VOTERS
                value: "1@broker:9093"
              - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                value: "1"
              - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
                value: "1"
              - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
                value: "1"
              - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
                value: "0"
              - name: KAFKA_NUM_PARTITIONS
                value: "1"