#
#  docker-compose.yaml
#  Progetto di Distributed Systems and Big Data
#  Anno Accademico 2024-25
#  (C) 2024 Luca Montera, Alessio Giordano
#
#  Created by Luca Montera on 24/11/24.
#

services:
    monitor:
        container_name: monitor
        image: prom/prometheus
        user: root # err="open /etc/prometheus/prometheus.yml: permission denied"
        ports:
        - "9090:9090"
        volumes:
        - monitor_prometheus_data:/prometheus
        - ./Monitor/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
        - whyfinance-network
#---####################################
    proxy:
        container_name: proxy
        build:
            context: ../
            dockerfile: Containers/Proxy/Dockerfile
        ports:
        - "${PROXY_PORT}:${PROXY_PORT}" # host:container
        - "9080:9080"
        environment:
        - PROXY_PORT=${PROXY_PORT} #------------------------------------------------------
        - STOCKS_PORT=${STOCKS_PORT}
        - USERS_PORT=${USERS_PORT}
        - MONITOR_SERVICE_NAME=proxy #----------------------------------------------------
        - MONITOR_SERVICE_NODE=proxy_1
        - MONITOR_SERVICE_PORT=9080
        networks:
        - whyfinance-network
        depends_on:
        - users
        - stocks
        - crawler
        restart: always
#---####################################
    broker:
        container_name: broker
        image: apache/kafka:3.7.2
        ports:
        - "9092:9092"
        - "9093:9093"
        networks:
        - whyfinance-network
        environment:
        - KAFKA_NODE_ID=1 #---------------------------------------------------------------
        - KAFKA_PROCESS_ROLES=broker,controller
        - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
        - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        - KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker:9093
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
        - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
        - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
        - KAFKA_NUM_PARTITIONS=1
        restart: always
#---------------------------------------
    broker_init:
        container_name: broker_init
        build:
            context: ../
            dockerfile: Containers/Broker/Dockerfile
        networks:
        - whyfinance-network
        environment:
        - KAFKA_BROKERS=${KAFKA_BROKERS} #------------------------------------------------
        - KAFKA_TOPICS=${KAFKA_TOPICS}
        depends_on:
        - broker
        restart: on-failure
#---####################################
    circuit_breaker_redis:
        container_name: circuit_breaker_redis
        image: redis:alpine
        ports:
        - 30111:6379 # host:container
        networks:
        - whyfinance-network
        restart: always
#---------------------------------------
    circuit_breaker:
        container_name: circuit_breaker
        build:
            context: ../
            dockerfile: Containers/CircuitBreaker/Dockerfile
        environment:
        - REDIS_PORT=${REDIS_PORT} #------------------------------------------------------
        - CIRCUIT_BREAKER_PORT=${CIRCUIT_BREAKER_PORT}
        ports:
        - "${CIRCUIT_BREAKER_PORT}:${CIRCUIT_BREAKER_PORT}"
        depends_on:
        - circuit_breaker_redis
        networks:
        - whyfinance-network
        restart: always
#---####################################
    crawler:
        container_name: crawler
        build:
            context: ../
            dockerfile: Containers/Crawler/Dockerfile
        ports:
        - "9081:9081"
        environment:
        - USERS_DB_HOST=${USERS_DB_HOST} #------------------------------------------------
        - USERS_DB_PORT=${USERS_DB_PORT}
        - USERS_DB_USER=${USERS_DB_USER}
        - USERS_DB_PASSWORD=${USERS_DB_PASSWORD}
        - USERS_DB_NAME=${USERS_DB_NAME}
        - STOCKS_DB_HOST=${STOCKS_DB_HOST} #----------------------------------------------
        - STOCKS_DB_PORT=${STOCKS_DB_PORT}
        - STOCKS_DB_USER=${STOCKS_DB_USER}
        - STOCKS_DB_PASSWORD=${STOCKS_DB_PASSWORD}
        - STOCKS_DB_NAME=${STOCKS_DB_NAME}
        - CIRCUIT_BREAKER_PORT=${CIRCUIT_BREAKER_PORT} #----------------------------------
        - CRAWLER_TIME_INTERVAL=${CRAWLER_TIME_INTERVAL} #--------------------------------
        - KAFKA_BROKERS=${KAFKA_BROKERS} #------------------------------------------------
        - KAFKA_ACKS=all # Notifications should be reliable
        - KAFKA_IN_FLIGHT_REQUESTS=1 # Ensure ordering of messages
        - KAFKA_LINGER=0 # Latency is more important than throughput
        - KAFKA_RETRIES=3
        - KAFKA_GROUP_ID=crawler
        - KAFKA_TOPICS=crawler
        - KAFKA_POLLING_INTERVAL=1.0
        - MONITOR_SERVICE_NAME=crawler #--------------------------------------------------
        - MONITOR_SERVICE_NODE=crawler_1
        - MONITOR_SERVICE_PORT=9081
        depends_on:
            users_database_init:
                condition: service_started
            stocks_database_init:
                condition: service_started
            broker_init:
                condition: service_started
        networks:
        - whyfinance-network
        restart: on-failure
#---####################################
    alert:
        container_name: alert
        build:
            context: ../
            dockerfile: Containers/Alert/Dockerfile
        environment:
        - DB_HOST=${USERS_DB_HOST} #------------------------------------------------------
        - DB_PORT=${USERS_DB_PORT}
        - DB_USER=${USERS_DB_USER}
        - DB_PASSWORD=${USERS_DB_PASSWORD}
        - DB_NAME=${USERS_DB_NAME}
        - KAFKA_BROKERS=${KAFKA_BROKERS} #------------------------------------------------
        - KAFKA_ACKS=all # Notifications should be reliable
        - KAFKA_LINGER=0 # Latency is more important than throughput
        - KAFKA_BATCH_SIZE=128000 # 128KB
        - KAFKA_RETRIES=3
        - KAFKA_GROUP_ID=alert
        - KAFKA_TOPICS=alert
        - KAFKA_POLLING_INTERVAL=1.0
        depends_on:
            users_database_init:
                condition: service_started
            stocks_database_init:
                condition: service_started
            broker_init:
                condition: service_started
        networks:
        - whyfinance-network
        restart: on-failure
#---####################################
    notification_center:
        container_name: notification_center
        build:
            context: ../
            dockerfile: Containers/NotificationCenter/Dockerfile
        environment:
        - CIRCUIT_BREAKER_PORT=${CIRCUIT_BREAKER_PORT} #----------------------------------
        - KAFKA_BROKERS=${KAFKA_BROKERS} #------------------------------------------------
        - KAFKA_GROUP_ID=notification_center
        - KAFKA_TOPICS=notification_center
        - KAFKA_POLLING_INTERVAL=1.0
        - APNS_ENDPOINT=${APNS_ENDPOINT} #------------------------------------------------
        depends_on:
            users_database_init:
                condition: service_started
            stocks_database_init:
                condition: service_started
            broker_init:
                condition: service_started
        networks:
        - whyfinance-network
        restart: on-failure
#---####################################
    users_database:
        container_name: users_database
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${USERS_DB_PASSWORD} #-----------------------------------
            MYSQL_DATABASE: ${USERS_DB_NAME}
        ports:
        - "3306:3306"
        volumes:
        - users_mysql_data:/var/lib/mysql
        networks:
        - whyfinance-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${USERS_DB_PASSWORD:-root}"]
            interval: 10s
            timeout: 60s
            retries: 20
            start_period: 60s
        restart: always
#---------------------------------------
    users_database_init:
        container_name: users_database_init
        build:
            context: ../
            dockerfile: Containers/UserDatabase/Dockerfile
        environment:
        - DB_HOST=${USERS_DB_HOST} #------------------------------------------------------
        - DB_PORT=${USERS_DB_PORT}
        - DB_USER=${USERS_DB_USER}
        - DB_PASSWORD=${USERS_DB_PASSWORD}
        - DB_NAME=${USERS_DB_NAME}
        networks:
        - whyfinance-network
        depends_on:
            users_database:
                condition: service_healthy
#---------------------------------------
    users_redis:
        container_name: users_redis
        image: redis:alpine
        ports:
        - 30113:6379 # host:container
        networks:
        - whyfinance-network
        restart: always
#---------------------------------------
    users:
        container_name: users
        build:
            context: ../
            dockerfile: Containers/Users/Dockerfile
        ports:
        - "${USERS_PORT}:50051"
        environment:
        - DB_HOST=${USERS_DB_HOST} #------------------------------------------------------
        - DB_PORT=${USERS_DB_PORT}
        - DB_USER=${USERS_DB_USER}
        - DB_PASSWORD=${USERS_DB_PASSWORD}
        - DB_NAME=${USERS_DB_NAME}
        - USERS_PORT=${USERS_PORT} #------------------------------------------------------
        - REDIS_PORT=${REDIS_PORT} #------------------------------------------------------
        - KAFKA_BROKERS=${KAFKA_BROKERS} #------------------------------------------------
        - KAFKA_ACKS=1 # Absolute reliability is not a concern
        - KAFKA_IN_FLIGHT_REQUESTS=1 # Ensure ordering of messages
        - KAFKA_LINGER=0 # Latency is more important than throughput
        - KAFKA_RETRIES=3
        depends_on:
            users_redis:
                condition: service_started
            users_database_init:
                condition: service_started
            broker_init:
                condition: service_started
        networks:
        - whyfinance-network
        restart: always
#---####################################
    stocks_database:
        container_name: stocks_database
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${STOCKS_DB_PASSWORD} #----------------------------------
            MYSQL_DATABASE: ${STOCKS_DB_NAME}
        ports:
        - "3307:3306"
        volumes:
        - stocks_mysql_data:/var/lib/mysql
        networks:
        - whyfinance-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${STOCKS_DB_PASSWORD:-root}"]
            interval: 10s
            timeout: 60s
            retries: 20
            start_period: 60s
        restart: always
#---------------------------------------
    stocks_database_init:
        container_name: stocks_database_init
        build:
            context: ../
            dockerfile: Containers/StockDatabase/Dockerfile
        environment:
        - DB_HOST=${STOCKS_DB_HOST} #-----------------------------------------------------
        - DB_PORT=${STOCKS_DB_PORT}
        - DB_USER=${STOCKS_DB_USER}
        - DB_PASSWORD=${STOCKS_DB_PASSWORD}
        - DB_NAME=${STOCKS_DB_NAME}
        networks:
        - whyfinance-network
        depends_on:
            stocks_database:
                condition: service_healthy
#---------------------------------------
    stocks_redis:
        container_name: stocks_redis
        image: redis:alpine
        ports:
        - 30114:6379 # host:container
        networks:
        - whyfinance-network
        restart: always
#---------------------------------------
    stocks:
        container_name: stocks
        build:
            context: ../
            dockerfile: Containers/Stocks/Dockerfile
        ports:
        - "${STOCKS_PORT}:50052"
        environment:
        - DB_HOST=${STOCKS_DB_HOST} #-----------------------------------------------------
        - DB_PORT=${STOCKS_DB_PORT}
        - DB_USER=${STOCKS_DB_USER}
        - DB_PASSWORD=${STOCKS_DB_PASSWORD}
        - DB_NAME=${STOCKS_DB_NAME}
        - STOCKS_PORT=${STOCKS_PORT} #----------------------------------------------------
        - REDIS_PORT=${REDIS_PORT}
        depends_on:
            stocks_redis:
                condition: service_started
            stocks_database_init:
                condition: service_started
        networks:
        - whyfinance-network
        restart: always
########################################
networks:
    whyfinance-network:
        driver: bridge
########################################
volumes:
    monitor_prometheus_data:
    users_mysql_data:
    stocks_mysql_data: