#
#  kind-config.yaml
#  Progetto di Distributed Systems and Big Data
#  Anno Accademico 2024-25
#  (C) 2024 Luca Montera, Alessio Giordano
#
#  Created by Alessio Giordano on 09/01/25.
#

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: why-finance
nodes:
- role: control-plane
  extraMounts:
  - hostPath: "${WHYFINANCE_PATH}"
    containerPath: /why-finance
- role: worker
  labels:
      custom-label: "worker"
  extraMounts:
  - hostPath: "${WHYFINANCE_PATH}"
    containerPath: /why-finance
  extraPortMappings:
  - containerPort: 30080 # Proxy (Flask)
    hostPort: 80
  - containerPort: 30090 # Monitor (Prometheus)
    hostPort: 9090