# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stocks_pb2 as stocks__pb2


class StockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLastStockValue = channel.unary_unary(
                '/stocks.StockService/GetLastStockValue',
                request_serializer=stocks__pb2.StockRequest.SerializeToString,
                response_deserializer=stocks__pb2.StockResponse.FromString,
                )
        self.CalculateAverageStockValue = channel.unary_unary(
                '/stocks.StockService/CalculateAverageStockValue',
                request_serializer=stocks__pb2.AverageStockRequest.SerializeToString,
                response_deserializer=stocks__pb2.StockResponse.FromString,
                )


class StockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLastStockValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateAverageStockValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLastStockValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastStockValue,
                    request_deserializer=stocks__pb2.StockRequest.FromString,
                    response_serializer=stocks__pb2.StockResponse.SerializeToString,
            ),
            'CalculateAverageStockValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateAverageStockValue,
                    request_deserializer=stocks__pb2.AverageStockRequest.FromString,
                    response_serializer=stocks__pb2.StockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stocks.StockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLastStockValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stocks.StockService/GetLastStockValue',
            stocks__pb2.StockRequest.SerializeToString,
            stocks__pb2.StockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalculateAverageStockValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stocks.StockService/CalculateAverageStockValue',
            stocks__pb2.AverageStockRequest.SerializeToString,
            stocks__pb2.StockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
