# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stocks.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstocks.proto\x12\x06stocks\"\x1e\n\x0cStockRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\"4\n\x13\x41verageStockRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x1e\n\rStockResponse\x12\r\n\x05value\x18\x01 \x01(\x01\x32\xa2\x01\n\x0cStockService\x12@\n\x11GetLastStockValue\x12\x14.stocks.StockRequest\x1a\x15.stocks.StockResponse\x12P\n\x1a\x43\x61lculateAverageStockValue\x12\x1b.stocks.AverageStockRequest\x1a\x15.stocks.StockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stocks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STOCKREQUEST']._serialized_start=24
  _globals['_STOCKREQUEST']._serialized_end=54
  _globals['_AVERAGESTOCKREQUEST']._serialized_start=56
  _globals['_AVERAGESTOCKREQUEST']._serialized_end=108
  _globals['_STOCKRESPONSE']._serialized_start=110
  _globals['_STOCKRESPONSE']._serialized_end=140
  _globals['_STOCKSERVICE']._serialized_start=143
  _globals['_STOCKSERVICE']._serialized_end=305
# @@protoc_insertion_point(module_scope)
