# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"\xae\x01\n\x0fUserDataRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x19\n\x0c\x64\x65vice_token\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tlow_value\x18\x04 \x01(\x02H\x01\x88\x01\x01\x12\x17\n\nhigh_value\x18\x05 \x01(\x02H\x02\x88\x01\x01\x42\x0f\n\r_device_tokenB\x0c\n\n_low_valueB\r\n\x0b_high_value\"(\n\x13UserDeletionRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\x1f\n\x0cUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc4\x01\n\x0bUserService\x12;\n\x0cRegisterUser\x12\x16.users.UserDataRequest\x1a\x13.users.UserResponse\x12\x39\n\nUpdateUser\x12\x16.users.UserDataRequest\x1a\x13.users.UserResponse\x12=\n\nDeleteUser\x12\x1a.users.UserDeletionRequest\x1a\x13.users.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERDATAREQUEST']._serialized_start=23
  _globals['_USERDATAREQUEST']._serialized_end=197
  _globals['_USERDELETIONREQUEST']._serialized_start=199
  _globals['_USERDELETIONREQUEST']._serialized_end=239
  _globals['_USERRESPONSE']._serialized_start=241
  _globals['_USERRESPONSE']._serialized_end=272
  _globals['_USERSERVICE']._serialized_start=275
  _globals['_USERSERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
