# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import watch_pb2 as watch__pb2


class WatchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLastStockValue = channel.unary_unary(
                '/watch.WatchService/GetLastStockValue',
                request_serializer=watch__pb2.StockRequest.SerializeToString,
                response_deserializer=watch__pb2.StockResponse.FromString,
                )
        self.CalculateAverageStockValue = channel.unary_unary(
                '/watch.WatchService/CalculateAverageStockValue',
                request_serializer=watch__pb2.AverageStockRequest.SerializeToString,
                response_deserializer=watch__pb2.StockResponse.FromString,
                )


class WatchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLastStockValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateAverageStockValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLastStockValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastStockValue,
                    request_deserializer=watch__pb2.StockRequest.FromString,
                    response_serializer=watch__pb2.StockResponse.SerializeToString,
            ),
            'CalculateAverageStockValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateAverageStockValue,
                    request_deserializer=watch__pb2.AverageStockRequest.FromString,
                    response_serializer=watch__pb2.StockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'watch.WatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WatchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLastStockValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/watch.WatchService/GetLastStockValue',
            watch__pb2.StockRequest.SerializeToString,
            watch__pb2.StockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalculateAverageStockValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/watch.WatchService/CalculateAverageStockValue',
            watch__pb2.AverageStockRequest.SerializeToString,
            watch__pb2.StockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
